### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by jbmoelker** [voorhoede/head-start#23]
# User story

As a website user,
I want to be able to search for content on the website,
so I can quickly find it without having to figure out how to navigate to it.

# Checklist

- [x] Requires API Routes to be available #47
- [ ] Requires build triggers to be configured #12 
- [ ] Requires build trigger(s) to have search indexing enabled
- [x] Use [DatoCMS search API](https://www.datocms.com/docs/site-search/base-integration). 
- [ ] Support different deploy environments (DatoCMS build triggers)?
- [x] Make search available as API endpoint (like `pages/api/search/[query].json.ts`)?
- [x] Make available as a dedicated page/route
- [ ] Make available as a (block, #20) component ([`<form role="search">`](https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/search.html))?
- [x] Support [OpenSearch](https://developer.mozilla.org/en-US/docs/Web/OpenSearch) meta file and tag (linked to page/route)
- [x] Default value to `?q=` parameter on page?
- [x] Excludes content outside `<main>` element (like site header, footer texts)
- [x] Search results link to pages using [Text fragments](https://developer.mozilla.org/en-US/docs/Web/Text_fragments) so browsers can highlight and scroll to the query matches
- [x] Documentation of the different search features (`docs/search.md`)
