### ISSUE TITLE
Site structure

### ISSUE THREAD

**Issue by jbmoelker** [voorhoede/head-start#6]
# User story

As a Marketer,
I want the site to be properly structured for SEO and A11y means.

# Checklist

Before starting development:

- ~~Define logical page structure with tree diagram~~ (up to project team using Head Start)
- ~~Define clean URLs, ask Marketer to include necessary keywords~~ (up to project team using Head Start)

On page:

- [ ] Set breadcrumbs (overlaps with #13)
- [ ] Add page heading structure (Only 1 H1, followed by H2, H3, H4 etc.) (validated by #100)
- [ ] Add Alt attributes to images (validated by #100)
