### ISSUE TITLE
Missing docs

### ISSUE THREAD

**Issue by jbmoelker** [voorhoede/head-start#71]
- ~~`docs/architecture.md`: add more detail, see [comment](https://github.com/voorhoede/head-start/issues/71#issuecomment-1833255003)~~ (moved to separate issue #212)
- [x] `docs/a11y.md`: linting, skip links, required alt texts, semantics, native elements with built-in a11y, css helpers; (see #99)
- [x] `docs/getting-started.md`: use template, create Cloudflare and DatoCMS instance, configure; (see #90)
- ~~`docs/icons.md`: directory, sprite, component (see [project structure](https://github.com/voorhoede/head-start/blob/main/docs/project-structure.md) and [icon component](https://github.com/voorhoede/head-start/blob/main/src/components/Icon/README.md) for now)~~ (moved to separate issue #210)
- [x] `docs/seo.md`: DatoCMS SEO preferences, SEO fields, SEO head; (see #75)
- [x] `docs/blocks-and-components.md` (see #79)
- [x] `docs/cms-content-modelling.md` (see #88)
- [x] `docs/cms-data-loading.md` (see #78)
- [ ] `docs/project-structure.md`: update with path aliases, and conventions (`.client.ts`, `.fragment|query.graphql`, `.partial.astro`, `/api/...`), mention `create:*` scripts (see #82).
- [x] `docs/routing.md`: nested, api, 404 pages & middleware, i18n, redirects (#64)
- [x] `docs/upgrade.md`: (see #191), (linking migrations is moved to separate issue #211)
